### ISSUE TITLE
First loom option should be 0.4-SNAPSHOT as that's the recommended version

### ISSUE THREAD

**Issue by nskobelevs** [ExtraCrafTX/GeneratorFabricMod#14]
This is more of a quality of life issue than an actual bug.

According to [this](https://modmuss50.me/fabric.html?&version=1.16.1) the recommended Loom version is 0.4-SNAPSHOT so shouldn't the first loom option to pop up be specifically that?

Thanks.

**Comment by ExtraCrafTX** [comment]
It should be the default that is selected already?

If you mean it should be the first on the list, I suppose so, but I'd have to some sort of sorting for it. At the moment they are just ordered in the same order that they were released. This is why it is lower down on the list.

**Comment by nskobelevs** [comment]
>At the moment they are just ordered in the same order that they were released
That's fair enough.

In theory you might not even need to sort anything, just offset the list so that 0.4-SNAPSHOT is the first one on the list.

Anyways, this is not a breaking bug so you're free to close the issue

**Comment by ExtraCrafTX** [comment]
I mean if it would be an improvement I would like to make, although at the moment I'm not sure I understand the issue.

You mean how 0.4.10 currently appears above it? If so, that is simply because the list wraps around and the selected item has a buffer of one item from the ends of the list, so the default will inevitably be the second item visible. Since it wraps around, offsetting the list would do nothing.  
This is also the case with all the other lists. I feel having the one item buffer helps indicate that there are more items in that direction.

I may be completely misunderstanding the issue though.

**Comment by nskobelevs** [comment]
I think I'm just bad at explaining it.

The issue is that then Loom version selector prompt, starts with the cursor on 0.2.6-SNAPSHOT. My suggestion is that since 0.4-SNAPSHOT is the recommended version, the prompt should start on that so that the user can just hit [Enter] without having to scroll.

This also comes from a new user point of view, the intuitive idea is that the first option is the one you should be using. Inexperienced Fabric modders might assume that they should be using 0.2.6-SNAPSHOT because it's the first one shown to them.

**Current:**
![Current](https://user-images.githubusercontent.com/34107736/86165987-feace700-bb0b-11ea-8591-a1772e98f55a.png)

**Recommendation:**
![Recommendation](https://user-images.githubusercontent.com/34107736/86166031-0ec4c680-bb0c-11ea-9136-7e16f863b557.png)

**Comment by ExtraCrafTX** [comment]
Ah ok! Yes, I completely misunderstood, not because you are bad at explaining, simply because you are using an older version! The latest version should correctly have 0.4-SNAPSHOT selected.

**Comment by nskobelevs** [comment]
Ahh yes, that's perfect.

I'd suggest including the version number somewhere in the final release then. Would decrease time wasting issues like my one since could have been fixed.
