### ISSUE TITLE
Cannot run it. Class files compiled with newer version. Except I AM on public release.

### ISSUE THREAD

**Issue by TybaIt** [ExtraCrafTX/GeneratorFabricMod#5]
Class files compiled with newer version? 
https://i.imgur.com/T646iKl.png

Tryint to update java via control panel. 
https://i.imgur.com/s2YpL6S.png

I also tried reinstalling with installer.

My guess is you are running a development JNI release?

**Comment by ExtraCrafTX** [comment]
The issue is not JNI, its the JRE. I entirely forgot that my Linux development environment was running Java 9. I will update it to use Java 8 again. In the mean time you can use version 0.1.1 which is the exact same in terms of features, the only difference being you will need to allow executing the generated `gradlew` if you are on Linux.

**Comment by Xephobia** [comment]
@ExtraCrafTX does that mean that if i pick hava 9, it will work?

**Comment by Xephobia** [comment]
wait a minute, how to get java 9

**Comment by ExtraCrafTX** [comment]
It should. Either way, rather than getting a new java version, for now I recommend just using v0.1.1 rather than the latest. Sorry that this is taking so long :/

**Comment by ExtraCrafTX** [comment]
@TybaIt @Xephobia Please try the latest version to see if that works for you!
